= AsciiDoc Reader

This plugin allows you to use https://asciidoc.org/[AsciiDoc] to write your
posts. File extension should be `.asc`, `.adoc`, or `.asciidoc`.

== Dependency

There are two command line utilities commonly used to render AsciiDoc:
`asciidoc` and `asciidoctor`. One of the two will need to be installed and on
the PATH.

**Note**: The `asciidoctor` utility is recommended since the original
`asciidoc` is no longer maintained.

== Settings

========================================  =======================================================
Setting name (followed by default value)  What does it do?
========================================  =======================================================
``ASCIIDOC_CMD = 'asciidoc'``             Selects which utility to use for rendering. Will
                                          autodetect utility if not provided.
``ASCIIDOC_OPTIONS = []``                 A list of options to pass to AsciiDoc. See the `manpage
                                          <http://www.methods.co.nz/asciidoc/manpage.html>`_.
========================================  =======================================================

== Example file header

Following the https://docs.getpelican.com/en/latest/content.html#file-metadata[example]
in the main pelican documentation:

[source,asciidoc]
----
= My super title

:date: 2010-10-03 10:20
:modified: 2010-10-04 18:40
:tags: thats, awesome
:category: yeah
:slug: my-super-post
:authors: Alexis Metaireau, Conan Doyle
:summary: Short version for index and feeds

== title level 2

and so on...
----

== Acknowledgements

Thanks to whoever wrote the original asciidoc reader code in
https://github.com/getpelican/pelican-plugins/[]; a lot of it lives on in this
package.

